set(TESTANIMATION_WITH_SPLITTER_NAME testAnimWithSplitter)				#Naziv prvog projekta u solution-u

file(GLOB TESTANIMATION_WITH_SPLITTER_SOURCES  ${CMAKE_CURRENT_LIST_DIR}/src/*.cpp)
file(GLOB TESTANIMATION_WITH_SPLITTER_INCS  ${CMAKE_CURRENT_LIST_DIR}/src/*.h)
set(TESTANIMATION_WITH_SPLITTER_PLIST  ${CMAKE_CURRENT_LIST_DIR}/src/Info.plist)
file(GLOB TESTANIMATION_WITH_SPLITTER_INC_TD  ${MY_INC}/td/*.h)
file(GLOB TESTANIMATION_WITH_SPLITTER_INC_GUI ${MY_INC}/gui/*.h)

# add executable
add_executable(${TESTANIMATION_WITH_SPLITTER_NAME} ${TESTANIMATION_WITH_SPLITTER_INCS} ${TESTANIMATION_WITH_SPLITTER_SOURCES} ${TESTANIMATION_WITH_SPLITTER_INC_TD}  ${TESTANIMATION_WITH_SPLITTER_INC_GUI})

source_group("inc"            FILES ${TESTANIMATION_WITH_SPLITTER_INCS})
source_group("inc\\td"        FILES ${TESTANIMATION_WITH_SPLITTER_INC_TD})
source_group("inc\\gui"        FILES ${TESTANIMATION_WITH_SPLITTER_INC_GUI})
source_group("src"            FILES ${TESTANIMATION_WITH_SPLITTER_SOURCES})

target_link_libraries(${TESTANIMATION_WITH_SPLITTER_NAME} debug ${MU_LIB_DEBUG} debug ${NATGUI_LIB_DEBUG} 
										optimized ${MU_LIB_RELEASE} optimized ${NATGUI_LIB_RELEASE})

setTargetPropertiesForGUIApp(${TESTANIMATION_WITH_SPLITTER_NAME} ${TESTANIMATION_WITH_SPLITTER_PLIST})

setIDEPropertiesForGUIExecutable(${TESTANIMATION_WITH_SPLITTER_NAME} ${CMAKE_CURRENT_LIST_DIR})

setPlatformDLLPath(${TESTANIMATION_WITH_SPLITTER_NAME})
