set(TESTSPLITANDPROPEDIT2_NAME testSplitAndPropEdit2)				#Naziv prvog projekta u solution-u

file(GLOB TESTSPLITANDPROPEDIT2_SOURCES  ${CMAKE_CURRENT_LIST_DIR}/src/*.cpp)
file(GLOB TESTSPLITANDPROPEDIT2_INCS  ${CMAKE_CURRENT_LIST_DIR}/src/*.h)
file(GLOB TESTSPLITANDPROPEDIT2_INC_MODEL  ${CMAKE_CURRENT_LIST_DIR}/src/model/*.h)
file(GLOB TESTSPLITANDPROPEDIT2_INC_PROPERTY  ${CMAKE_CURRENT_LIST_DIR}/src/property/*.h)
file(GLOB TESTSPLITANDPROPEDIT2_INC_TD  ${NATID_SDK_INC}/td/*.h)
file(GLOB TESTSPLITANDPROPEDIT2_INC_GUI ${NATID_SDK_INC}/gui/*.h)

#Application icon
set(TESTSPLITANDPROPEDIT2_PLIST  ${CMAKE_CURRENT_LIST_DIR}/res/appIcon/AppIcon.plist)
if(WIN32)
	set(TESTSPLITANDPROPEDIT2_WINAPP_ICON ${CMAKE_CURRENT_LIST_DIR}/res/appIcon/winAppIcon.rc)
else()
	set(TESTSPLITANDPROPEDIT2_WINAPP_ICON ${CMAKE_CURRENT_LIST_DIR}/res/appIcon/winAppIcon.cpp)
endif()

# add executable
add_executable(${TESTSPLITANDPROPEDIT2_NAME} ${TESTSPLITANDPROPEDIT2_INCS} ${TESTSPLITANDPROPEDIT2_INC_MODEL}  ${TESTSPLITANDPROPEDIT2_INC_PROPERTY}  ${TESTSPLITANDPROPEDIT2_SOURCES}
			${TESTSPLITANDPROPEDIT2_INC_TD}  ${TESTSPLITANDPROPEDIT2_INC_GUI}  ${TESTSPLITANDPROPEDIT2_WINAPP_ICON})

source_group("inc"            FILES ${TESTSPLITANDPROPEDIT2_INCS})
source_group("inc\\model"            FILES ${TESTSPLITANDPROPEDIT2_INC_MODEL})
source_group("inc\\property"            FILES ${TESTSPLITANDPROPEDIT2_INC_PROPERTY})
source_group("inc\\td"        FILES ${TESTSPLITANDPROPEDIT2_INC_TD})
source_group("inc\\gui"        FILES ${TESTSPLITANDPROPEDIT2_INC_GUI})
source_group("src"            FILES ${TESTSPLITANDPROPEDIT2_SOURCES})

target_link_libraries(${TESTSPLITANDPROPEDIT2_NAME} debug ${MU_LIB_DEBUG} debug ${NATGUI_LIB_DEBUG} 
										optimized ${MU_LIB_RELEASE}  optimized ${NATGUI_LIB_RELEASE})

setTargetPropertiesForGUIApp(${TESTSPLITANDPROPEDIT2_NAME} ${TESTSPLITANDPROPEDIT2_PLIST})

setAppIcon(${TESTSPLITANDPROPEDIT2_NAME} ${CMAKE_CURRENT_LIST_DIR})

setIDEPropertiesForGUIExecutable(${TESTSPLITANDPROPEDIT2_NAME} ${CMAKE_CURRENT_LIST_DIR})

setPlatformDLLPath(${TESTSPLITANDPROPEDIT2_NAME})
