set(TEST2DTRANSFORMATION_NAME test2DETFTransf)				#Naziv prvog projekta u solution-u

file(GLOB TEST2DTRANSFORMATION_SOURCES  ${CMAKE_CURRENT_LIST_DIR}/src/*.cpp)
file(GLOB TEST2DTRANSFORMATION_INCS  ${CMAKE_CURRENT_LIST_DIR}/src/*.h)
set(TEST2DTRANSFORMATION_PLIST  ${CMAKE_CURRENT_LIST_DIR}/src/Info.plist)
file(GLOB TEST2DTRANSFORMATION_INC_TD  ${MY_INC}/td/*.h)
file(GLOB TEST2DTRANSFORMATION_INC_GUI ${MY_INC}/gui/*.h)

# add executable
add_executable(${TEST2DTRANSFORMATION_NAME} ${TEST2DTRANSFORMATION_INCS} ${TEST2DTRANSFORMATION_SOURCES} ${TEST2DTRANSFORMATION_INC_TD}  ${TEST2DTRANSFORMATION_INC_GUI})

source_group("inc"            FILES ${TEST2DTRANSFORMATION_INCS})
source_group("inc\\td"        FILES ${TEST2DTRANSFORMATION_INC_TD})
source_group("inc\\gui"        FILES ${TEST2DTRANSFORMATION_INC_GUI})
source_group("src"            FILES ${TEST2DTRANSFORMATION_SOURCES})

target_link_libraries(${TEST2DTRANSFORMATION_NAME} debug ${MU_LIB_DEBUG} debug ${NATGUI_LIB_DEBUG} 
										optimized ${MU_LIB_RELEASE} optimized ${NATGUI_LIB_RELEASE})

setTargetPropertiesForGUIApp(${TEST2DTRANSFORMATION_NAME} ${TEST2DTRANSFORMATION_PLIST})

setIDEPropertiesForGUIExecutable(${TEST2DTRANSFORMATION_NAME} ${CMAKE_CURRENT_LIST_DIR})

setPlatformDLLPath(${TEST2DTRANSFORMATION_NAME})
