#pragma once
#include <gui/View.h>
#include <gui/Label.h>
#include <gui/Button.h>
#include <gui/LineEdit.h>
#include <gui/TextEdit.h>
#include <gui/NumericEdit.h>
#include <gui/CheckBox.h>
#include <gui/GridLayout.h>
#include <gui/GridComposer.h>
#include "EQPlugin.h"

extern td::String earthquakeData;

class ViewOptions : public gui::View
{
private:
protected:
    gui::Label _lblName;
    gui::LineEdit _editName;
    gui::Label _lblMaxIter;
    gui::Label _lbldT;
    gui::Label _llblEndT;
    gui::Label _lblAccel;
    gui::NumericEdit _neMaxIter;
    gui::NumericEdit _neDeltaTime;
    gui::NumericEdit _neEndTime;
    gui::CheckBox _useAccelorometerData;
    gui::TextEdit _te;
    gui::GridLayout _gl;
    Options _options;
    
    td::UINT4 _wndID;
protected:
    
public:
    ViewOptions()
    : _lblName(tr("Model name:"))
    , _lblMaxIter(tr("Max iters:"))
    , _lbldT(tr("dT:"))
    , _llblEndT(tr("End time:"))
    , _neMaxIter(td::int4)
    , _neDeltaTime(td::real4, gui::LineEdit::Messages::DoNotSend, false, tr("Integration time"), 3)
    , _neEndTime(td::real4, gui::LineEdit::Messages::DoNotSend, true, tr("Integration time"), 3)
    , _useAccelorometerData(tr("Use accelorometer data:"))
    , _gl(5,4)
    {
        _editName = "Earth-quake model generated by the plugin ocnverter";
        _neMaxIter.setValue(td::INT4(10));
        _neDeltaTime.setValue(0.001f);
        _neEndTime.setValue(60.f);
        _useAccelorometerData.setChecked(true);
        _te.setText(earthquakeData);
        
        gui::GridComposer gc(_gl);
        gc.appendRow(_lblName); gc.appendCol(_editName, 0);
        gc.appendRow(_lblMaxIter) << _neMaxIter;
        gc.appendRow(_lbldT) << _neDeltaTime << _llblEndT << _neEndTime;
        gc.appendRow(_useAccelorometerData, 0);
        gc.appendRow(_te, 0); //0:span to end
        
        setLayout(&_gl);
    }
    
    const Options& getOptions()
    {
        _options.modelName = _editName.getText();
        _options.maxIter = _neMaxIter.getValue().i4Val();
        _options.dTime = _neDeltaTime.getValue().r4Val();
        _options.endTime = _neEndTime.getValue().r4Val();
        _options.useAccelorometerData = _useAccelorometerData.isChecked();
        if (_options.useAccelorometerData)
            _options.accelorometerData = _te.getText();
        else
            _options.accelorometerData.clean();
        return _options;
    }
    
};
