set(TESTSIMPLEDYNTAB_NAME testSimpleDynTab)				#Naziv prvog projekta u solution-u

file(GLOB TESTSIMPLEDYNTAB_SOURCES  ${CMAKE_CURRENT_LIST_DIR}/src/*.cpp)
file(GLOB TESTSIMPLEDYNTAB_INCS  ${CMAKE_CURRENT_LIST_DIR}/src/*.h)
file(GLOB TESTSIMPLEDYNTAB_INC_TD  ${MY_INC}/td/*.h)
file(GLOB TESTSIMPLEDYNTAB_INC_GUI ${MY_INC}/gui/*.h)

#Application icon
set(TESTSIMPLEDYNTAB_PLIST  ${CMAKE_CURRENT_LIST_DIR}/res/appIcon/AppIcon.plist)
if(WIN32)
	set(TESTSIMPLEDYNTAB_WINAPP_ICON ${CMAKE_CURRENT_LIST_DIR}/res/appIcon/winAppIcon.rc)
else()
	set(TESTSIMPLEDYNTAB_WINAPP_ICON ${CMAKE_CURRENT_LIST_DIR}/res/appIcon/winAppIcon.cpp)
endif()

# add executable
add_executable(${TESTSIMPLEDYNTAB_NAME} ${TESTSIMPLEDYNTAB_INCS} ${TESTSIMPLEDYNTAB_SOURCES} ${TESTSIMPLEDYNTAB_INC_TD}  
		${TESTSIMPLEDYNTAB_INC_GUI} ${TESTSIMPLEDYNTAB_WINAPP_ICON})

source_group("inc"            FILES ${TESTSIMPLEDYNTAB_INCS})
source_group("src"            FILES ${TESTSIMPLEDYNTAB_SOURCES})
source_group("inc\\td"        FILES ${TESTSIMPLEDYNTAB_INC_TD})
source_group("inc\\gui"        FILES ${TESTSIMPLEDYNTAB_INC_GUI})

target_link_libraries(${TESTSIMPLEDYNTAB_NAME} debug ${MU_LIB_DEBUG} debug ${NATGUI_LIB_DEBUG} 
									optimized ${MU_LIB_RELEASE}  optimized ${NATGUI_LIB_RELEASE})

setTargetPropertiesForGUIApp(${TESTSIMPLEDYNTAB_NAME} ${TESTSIMPLEDYNTAB_PLIST})

setAppIcon(${TESTSIMPLEDYNTAB_NAME} ${CMAKE_CURRENT_LIST_DIR})

setIDEPropertiesForGUIExecutable(${TESTSIMPLEDYNTAB_NAME} ${CMAKE_CURRENT_LIST_DIR})

setPlatformDLLPath(${TESTSIMPLEDYNTAB_NAME})
