set(TESTGLANIMATION3DFLAT_NAME testGLAnimationFlat)				#Naziv prvog projekta u solution-u

file(GLOB TESTGLANIMATION3DFLAT_SOURCES  ${CMAKE_CURRENT_LIST_DIR}/src/*.cpp)
file(GLOB TESTGLANIMATION3DFLAT_INCS  ${CMAKE_CURRENT_LIST_DIR}/src/*.h)
set(TESTGLANIMATION3DFLAT_PLIST  ${CMAKE_CURRENT_LIST_DIR}/src/Info.plist)
file(GLOB TESTGLANIMATION3DFLAT_INC_TD  ${MY_INC}/td/*.h)
file(GLOB TESTGLANIMATION3DFLAT_INC_GUI ${MY_INC}/gui/*.h)
file(GLOB TESTGLANIMATION3DFLAT_INC_GUI_GL ${MY_INC}/gui/gl/*.h)

# add executable
add_executable(${TESTGLANIMATION3DFLAT_NAME} ${TESTGLANIMATION3DFLAT_INCS} ${TESTGLANIMATION3DFLAT_SOURCES} ${TESTGLANIMATION3DFLAT_INC_TD} ${TESTGLANIMATION3DFLAT_INC_GUI} ${TESTGLANIMATION3DFLAT_INC_GUI_GL})

source_group("inc"            FILES ${TESTGLANIMATION3DFLAT_INCS})
source_group("src"            FILES ${TESTGLANIMATION3DFLAT_SOURCES})
source_group("inc\\td"        FILES ${TESTGLANIMATION3DFLAT_INC_TD})
source_group("inc\\gui"        FILES ${TESTGLANIMATION3DFLAT_INC_GUI})
source_group("inc\\gl"        FILES ${TESTGLANIMATION3DFLAT_INC_GUI_GL})

target_link_libraries(${TESTGLANIMATION3DFLAT_NAME} debug ${MU_LIB_DEBUG} optimized ${MU_LIB_RELEASE} 
									debug ${NATGUI_LIB_DEBUG} optimized ${NATGUI_LIB_RELEASE} 
								debug ${NATGL_LIB_DEBUG} optimized ${NATGL_LIB_RELEASE})

addOpenGLLibraries(${TESTGLANIMATION3DFLAT_NAME})

setTargetPropertiesForGUIApp(${TESTGLANIMATION3DFLAT_NAME} ${TESTGLANIMATION3DFLAT_PLIST})

setIDEPropertiesForGUIExecutable(${TESTGLANIMATION3DFLAT_NAME} ${CMAKE_CURRENT_LIST_DIR})

setPlatformDLLPath(${TESTGLANIMATION3DFLAT_NAME})



