set(TEST2DETFTRANSFWSPLITTER_NAME test2DETFTrWSplitter)				#Naziv prvog projekta u solution-u

file(GLOB TEST2DETFTRANSFWSPLITTER_SOURCES  ${CMAKE_CURRENT_LIST_DIR}/src/*.cpp)
file(GLOB TEST2DETFTRANSFWSPLITTER_INCS  ${CMAKE_CURRENT_LIST_DIR}/src/*.h)
set(TEST2DETFTRANSFWSPLITTER_PLIST  ${CMAKE_CURRENT_LIST_DIR}/src/Info.plist)
file(GLOB TEST2DETFTRANSFWSPLITTER_INC_TD  ${MY_INC}/td/*.h)
file(GLOB TEST2DETFTRANSFWSPLITTER_INC_GUI ${MY_INC}/gui/*.h)

# add executable
add_executable(${TEST2DETFTRANSFWSPLITTER_NAME} ${TEST2DETFTRANSFWSPLITTER_INCS} ${TEST2DETFTRANSFWSPLITTER_SOURCES} ${TEST2DETFTRANSFWSPLITTER_INC_TD}  ${TEST2DETFTRANSFWSPLITTER_INC_GUI})

source_group("inc"            FILES ${TEST2DETFTRANSFWSPLITTER_INCS})
source_group("inc\\td"        FILES ${TEST2DETFTRANSFWSPLITTER_INC_TD})
source_group("inc\\gui"        FILES ${TEST2DETFTRANSFWSPLITTER_INC_GUI})
source_group("src"            FILES ${TEST2DETFTRANSFWSPLITTER_SOURCES})

target_link_libraries(${TEST2DETFTRANSFWSPLITTER_NAME} debug ${MU_LIB_DEBUG} debug ${NATGUI_LIB_DEBUG} 
										optimized ${MU_LIB_RELEASE} optimized ${NATGUI_LIB_RELEASE})

setTargetPropertiesForGUIApp(${TEST2DETFTRANSFWSPLITTER_NAME} ${TEST2DETFTRANSFWSPLITTER_PLIST})

setIDEPropertiesForGUIExecutable(${TEST2DETFTRANSFWSPLITTER_NAME} ${CMAKE_CURRENT_LIST_DIR})

setPlatformDLLPath(${TEST2DETFTRANSFWSPLITTER_NAME})
