set(TESTGLANIMATION3DTEXTURE2_NAME testGLAnimation3DTexture2)				#Naziv prvog projekta u solution-u

file(GLOB TESTGLANIMATION3DTEXTURE2_SOURCES  ${CMAKE_CURRENT_LIST_DIR}/src/*.cpp)
file(GLOB TESTGLANIMATION3DTEXTURE2_INCS  ${CMAKE_CURRENT_LIST_DIR}/src/*.h)
set(TESTGLANIMATION3DTEXTURE2_PLIST  ${CMAKE_CURRENT_LIST_DIR}/src/Info.plist)
file(GLOB TESTGLANIMATION3DTEXTURE2_INC_TD  ${MY_INC}/td/*.h)
file(GLOB TESTGLANIMATION3DTEXTURE2_INC_GUI ${MY_INC}/gui/*.h)
file(GLOB TESTGLANIMATION3DTEXTURE2_INC_GUI_GL ${MY_INC}/gui/gl/*.h)

# add executable
add_executable(${TESTGLANIMATION3DTEXTURE2_NAME} ${TESTGLANIMATION3DTEXTURE2_INCS} ${TESTGLANIMATION3DTEXTURE2_SOURCES} ${TESTGLANIMATION3DTEXTURE2_INC_TD} ${TESTGLANIMATION3DTEXTURE2_INC_GUI} ${TESTGLANIMATION3DTEXTURE2_INC_GUI_GL})

source_group("inc"            FILES ${TESTGLANIMATION3DTEXTURE2_INCS})
source_group("src"            FILES ${TESTGLANIMATION3DTEXTURE2_SOURCES})
source_group("inc\\td"        FILES ${TESTGLANIMATION3DTEXTURE2_INC_TD})
source_group("inc\\gui"        FILES ${TESTGLANIMATION3DTEXTURE2_INC_GUI})
source_group("inc\\gl"        FILES ${TESTGLANIMATION3DTEXTURE2_INC_GUI_GL})

target_link_libraries(${TESTGLANIMATION3DTEXTURE2_NAME} debug ${MU_LIB_DEBUG} optimized ${MU_LIB_RELEASE} 
									debug ${NATGUI_LIB_DEBUG} optimized ${NATGUI_LIB_RELEASE} 
								debug ${NATGL_LIB_DEBUG} optimized ${NATGL_LIB_RELEASE})

addOpenGLLibraries(${TESTGLANIMATION3DTEXTURE2_NAME})

setTargetPropertiesForGUIApp(${TESTGLANIMATION3DTEXTURE2_NAME} ${TESTGLANIMATION3DTEXTURE2_PLIST})

setIDEPropertiesForGUIExecutable(${TESTGLANIMATION3DTEXTURE2_NAME} ${CMAKE_CURRENT_LIST_DIR})

setPlatformDLLPath(${TESTGLANIMATION3DTEXTURE2_NAME})



