set(FACEDETECTIONMT_NAME FaceDetectionMT)				#Naziv prvog projekta u solution-u

file(GLOB FACEDETECTIONMT_SOURCES  ${CMAKE_CURRENT_LIST_DIR}/src/*.cpp)
file(GLOB FACEDETECTIONMT_INCS  ${CMAKE_CURRENT_LIST_DIR}/src/*.h)
file(GLOB FACEDETECTIONMT_INC_TD  ${MY_INC}/td/*.h)
file(GLOB FACEDETECTIONMT_INC_GUI ${MY_INC}/gui/*.h)

file(GLOB FACEDETECTIONMT_INC_THREAD  ${MY_INC}/thread/*.h)
file(GLOB FACEDETECTIONMT_INC_CNT  ${MY_INC}/cnt/*.h)
file(GLOB FACEDETECTIONMT_INC_FO  ${MY_INC}/fo/*.h)
file(GLOB FACEDETECTIONMT_INC_MU  ${MY_INC}/mu/*.h)
file(GLOB FACEDETECTIONMT_INC_RND  ${MY_INC}/rnd/*.h)

file(GLOB FACEDETECTIONMT_INC_XML  ${MY_INC}/xml/*.h)

#Application icon
set(FACEDETECTIONMT_PLIST  ${CMAKE_CURRENT_LIST_DIR}/res/appIcon/AppIcon.plist)
if(WIN32)
	set(FACEDETECTIONMT_WINAPP_ICON ${CMAKE_CURRENT_LIST_DIR}/res/appIcon/winAppIcon.rc)
else()
	set(FACEDETECTIONMT_WINAPP_ICON ${CMAKE_CURRENT_LIST_DIR}/res/appIcon/winAppIcon.cpp)
endif()

# add executable
add_executable(${FACEDETECTIONMT_NAME} ${FACEDETECTIONMT_INCS} ${FACEDETECTIONMT_SOURCES} ${FACEDETECTIONMT_INC_TD} ${FACEDETECTIONMT_INC_THREAD} 
				${FACEDETECTIONMT_INC_CNT} ${FACEDETECTIONMT_INC_FO} ${FACEDETECTIONMT_INC_MU}
				 ${FACEDETECTIONMT_INC_GUI} ${FACEDETECTIONMT_INC_RND} 
				${FACEDETECTIONMT_INC_XML} ${FACEDETECTIONMT_WINAPP_ICON})

source_group("inc"            FILES ${FACEDETECTIONMT_INCS})
source_group("inc\\td"        FILES ${FACEDETECTIONMT_INC_TD})
source_group("inc\\cnt"        FILES ${FACEDETECTIONMT_INC_CNT})
source_group("inc\\fo"        FILES ${FACEDETECTIONMT_INC_FO})
source_group("inc\\mu"        FILES ${FACEDETECTIONMT_INC_MU})
source_group("inc\\gui"        FILES ${FACEDETECTIONMT_INC_GUI})
source_group("inc\\rnd"        FILES ${FACEDETECTIONMT_INC_RND})
source_group("inc\\thread"        FILES ${FACEDETECTIONMT_INC_THREAD})
source_group("inc\\xml"        FILES ${FACEDETECTIONMT_INC_XML})
source_group("src"            FILES ${FACEDETECTIONMT_SOURCES})

target_link_libraries(${FACEDETECTIONMT_NAME} debug ${MU_LIB_DEBUG} debug ${NATGUI_LIB_DEBUG} 
										optimized ${MU_LIB_RELEASE} optimized ${NATGUI_LIB_RELEASE})

setTargetPropertiesForGUIApp(${FACEDETECTIONMT_NAME} ${FACEDETECTIONMT_PLIST})

setAppIcon(${FACEDETECTIONMT_NAME} ${CMAKE_CURRENT_LIST_DIR})

setIDEPropertiesForGUIExecutable(${FACEDETECTIONMT_NAME} ${CMAKE_CURRENT_LIST_DIR})

setPlatformDLLPath(${FACEDETECTIONMT_NAME})
