set(FACEDETECTIONMT4_NAME FaceDetectionMT4)				#Naziv prvog projekta u solution-u

file(GLOB FACEDETECTIONMT4_SOURCES  ${CMAKE_CURRENT_LIST_DIR}/src/*.cpp)
file(GLOB FACEDETECTIONMT4_INCS  ${CMAKE_CURRENT_LIST_DIR}/src/*.h)
file(GLOB FACEDETECTIONMT4_INC_TD  ${MY_INC}/td/*.h)
file(GLOB FACEDETECTIONMT4_INC_GUI ${MY_INC}/gui/*.h)

file(GLOB FACEDETECTIONMT4_INC_THREAD  ${MY_INC}/thread/*.h)
file(GLOB FACEDETECTIONMT4_INC_CNT  ${MY_INC}/cnt/*.h)
file(GLOB FACEDETECTIONMT4_INC_FO  ${MY_INC}/fo/*.h)
file(GLOB FACEDETECTIONMT4_INC_MU  ${MY_INC}/mu/*.h)
file(GLOB FACEDETECTIONMT4_INC_RND  ${MY_INC}/rnd/*.h)

file(GLOB FACEDETECTIONMT4_INC_XML  ${MY_INC}/xml/*.h)

#Application icon
set(FACEDETECTIONMT4_PLIST  ${CMAKE_CURRENT_LIST_DIR}/res/appIcon/AppIcon.plist)
if(WIN32)
	set(FACEDETECTIONMT4_WINAPP_ICON ${CMAKE_CURRENT_LIST_DIR}/res/appIcon/winAppIcon.rc)
else()
	set(FACEDETECTIONMT4_WINAPP_ICON ${CMAKE_CURRENT_LIST_DIR}/res/appIcon/winAppIcon.cpp)
endif()

# add executable
add_executable(${FACEDETECTIONMT4_NAME} ${FACEDETECTIONMT4_INCS} ${FACEDETECTIONMT4_SOURCES} ${FACEDETECTIONMT4_INC_TD} ${FACEDETECTIONMT4_INC_THREAD} 
				${FACEDETECTIONMT4_INC_CNT} ${FACEDETECTIONMT4_INC_FO} ${FACEDETECTIONMT4_INC_MU}
				 ${FACEDETECTIONMT4_INC_GUI} ${FACEDETECTIONMT4_INC_RND} 
				${FACEDETECTIONMT4_INC_XML} ${FACEDETECTIONMT4_WINAPP_ICON})

source_group("inc"            FILES ${FACEDETECTIONMT4_INCS})
source_group("inc\\td"        FILES ${FACEDETECTIONMT4_INC_TD})
source_group("inc\\cnt"        FILES ${FACEDETECTIONMT4_INC_CNT})
source_group("inc\\fo"        FILES ${FACEDETECTIONMT4_INC_FO})
source_group("inc\\mu"        FILES ${FACEDETECTIONMT4_INC_MU})
source_group("inc\\gui"        FILES ${FACEDETECTIONMT4_INC_GUI})
source_group("inc\\rnd"        FILES ${FACEDETECTIONMT4_INC_RND})
source_group("inc\\thread"        FILES ${FACEDETECTIONMT4_INC_THREAD})
source_group("inc\\xml"        FILES ${FACEDETECTIONMT4_INC_XML})
source_group("src"            FILES ${FACEDETECTIONMT4_SOURCES})

target_link_libraries(${FACEDETECTIONMT4_NAME} debug ${MU_LIB_DEBUG} debug ${NATGUI_LIB_DEBUG} 
										optimized ${MU_LIB_RELEASE} optimized ${NATGUI_LIB_RELEASE})

setTargetPropertiesForGUIApp(${FACEDETECTIONMT4_NAME} ${FACEDETECTIONMT4_PLIST})

setAppIcon(${FACEDETECTIONMT4_NAME} ${CMAKE_CURRENT_LIST_DIR})

setIDEPropertiesForGUIExecutable(${FACEDETECTIONMT4_NAME} ${CMAKE_CURRENT_LIST_DIR})

setPlatformDLLPath(${FACEDETECTIONMT4_NAME})
