set(TESTWINDOWSANDDIALOGS_NAME testWindowsAndDialogs)				#Naziv prvog projekta u solution-u

file(GLOB TESTWINDOWSANDDIALOGS_SOURCES  ${CMAKE_CURRENT_LIST_DIR}/src/*.cpp)
file(GLOB TESTWINDOWSANDDIALOGS_INCS  ${CMAKE_CURRENT_LIST_DIR}/src/*.h)
set(TESTWINDOWSANDDIALOGS_PLIST  ${CMAKE_CURRENT_LIST_DIR}/src/Info.plist)
file(GLOB TESTWINDOWSANDDIALOGS_INC_TD  ${MY_INC}/td/*.h)
file(GLOB TESTWINDOWSANDDIALOGS_INC_GUI ${MY_INC}/gui/*.h)

# add executable
add_executable(${TESTWINDOWSANDDIALOGS_NAME} ${TESTWINDOWSANDDIALOGS_INCS} ${TESTWINDOWSANDDIALOGS_SOURCES} ${TESTWINDOWSANDDIALOGS_INC_TD}  ${TESTWINDOWSANDDIALOGS_INC_GUI})

source_group("inc"            FILES ${TESTWINDOWSANDDIALOGS_INCS})
source_group("inc\\td"        FILES ${TESTWINDOWSANDDIALOGS_INC_TD})
source_group("inc\\gui"        FILES ${TESTWINDOWSANDDIALOGS_INC_GUI})
source_group("src"            FILES ${TESTWINDOWSANDDIALOGS_SOURCES})

target_link_libraries(${TESTWINDOWSANDDIALOGS_NAME} debug ${MU_LIB_DEBUG} debug ${NATGUI_LIB_DEBUG} debug ${DP_LIB_DEBUG} 
											optimized ${MU_LIB_RELEASE} optimized ${NATGUI_LIB_RELEASE} optimized ${DP_LIB_RELEASE})

setTargetPropertiesForGUIApp(${TESTWINDOWSANDDIALOGS_NAME} ${TESTWINDOWSANDDIALOGS_PLIST})

setIDEPropertiesForGUIExecutable(${TESTWINDOWSANDDIALOGS_NAME} ${CMAKE_CURRENT_LIST_DIR})

setPlatformDLLPath(${TESTWINDOWSANDDIALOGS_NAME})
